#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# python-ptraceplus - Ptrace bindings + extra stuff
#
# Copyright (c) 2013 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import logging
from ptraceplus import __version__
from ptraceplus.common import setup_i18n
from ptraceplus.syscalls.helpers import convert_names, format_syscall
from ptraceplus.tracerplus import TracerPlus
from gettext import gettext as _

logging.basicConfig()

setup_i18n()

class TracerStats:
    __slots__ = ['n_procs', 'results']

    def __init__(self, n, r):
        self.n_procs = n
        self.results = r

class Tracer(TracerPlus):
    def __init__(self, args, verbose=False):
        TracerPlus.__init__(self, args)
        self._verbose = verbose
        self._results = {}
        self._selection = []

    @property
    def stats(self):
        results = [(n, c) for n, c in self._results.items()]
        return TracerStats(self.n_procs, sorted(results))

    def filter_syscalls(self, names):
        self._selection = convert_names(names)

    def _on_event(self, event):
        if self._verbose:
            print(event)

    def _on_syscall_enter(self, syscall):
        if self._verbose or syscall.num in self._selection:
            syscall.collect_params()
        if self._verbose:
            txt = "[{}] {} = ?"
            print(txt.format(syscall.pid, format_syscall(syscall, True)))

    def _on_syscall_exit(self, syscall):
        if self._verbose or syscall.num in self._selection:
            res = syscall.collect_result()
            if not syscall.name in self._results:
                self._results[syscall.name] = 0
            else:
                self._results[syscall.name] += 1
            txt = "[{}] {} = {}"
            print(txt.format(syscall.pid, format_syscall(syscall, True), res))

def format_tracer_stats(stats):
    print("----")
    print(_("Number of processes traced: {}").format(stats.n_procs))
    if stats.results:
        print(_("Syscalls statistics:"))
    for n, c in stats.results:
        print(" {:<24}: {}".format(n, c))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version=__version__)
    parser.add_argument('arguments',
                        nargs=argparse.REMAINDER,
                        help=_('arguments of the program'))
    parser.add_argument('--verbose', '-v',
                        action='store_true',
                        default=False,
                        help=_('verbose mode'))
    parser.add_argument('--syscall', '-S',
                        metavar='NAME',
                        action='append',
                        dest='syscalls',
                        default=[],
                        help=_('filter syscall by its name'))
    args = parser.parse_args()

    if len(args.arguments) == 0:
        parser.error(_('Missing argument(s)'))

    tracer = Tracer(args.arguments, args.verbose)
    tracer.filter_syscalls(args.syscalls)
    tracer.run()
    format_tracer_stats(tracer.stats)

# vim: ts=4 sts=4 sw=4 sta et ai
