#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# python-ptraceplus - Ptrace bindings + extra stuff
#
# Copyright (c) 2013 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import logging
from ptraceplus import __version__
from ptraceplus.common import setup_i18n
from ptraceplus.tracerplus import TracerPlus
from gettext import gettext as _

logging.basicConfig()

setup_i18n()

def format_tracer_stats(stats):
    print(_("Number of processes traced: {}").format(stats.n_procs))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version=__version__)
    parser.add_argument('arguments',
                        nargs=argparse.REMAINDER,
                        help=_('arguments of the program'))
    parser.add_argument('--verbose', '-v',
                        action='store_true',
                        default=False,
                        help=_('verbose mode'))
    args = parser.parse_args()

    if len(args.arguments) == 0:
        parser.error(_('Missing argument(s)'))

    tracer = TracerPlus(args.arguments)
    tracer.verbose = args.verbose
    tracer.run()
    format_tracer_stats(tracer.stats)

# vim: ts=4 sts=4 sw=4 sta et ai
